services:
  core:
    container_name: 'core'
    build: /ggleipnir-back/core
    ports:
      - "8080:8080"
    restart: always

  media:
    container_name: 'media'
    build: /ggleipnir-back/media
    ports:
      - "8090:8090"
    restart: always

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Secure123$
    networks:
      - minio_net

networks:
  minio_net: