name: ggleipnir_front
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  url_strategy: ^0.2.0
  http: ^1.2.0
  flutter_bloc: ^8.1.5
  bloc: ^8.1.3
  dimension: ^0.1.7
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  provider: ^6.1.2
  beamer: ^1.6.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - graphics/heart.svg
  fonts:
    - family: Roobert
      fonts:
        - asset: fonts/Roobert-Regular.ttf