name: ggleipnir_front
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  url_strategy: ^0.2.0
  http: ^1.2.0
  dimension: ^0.1.7
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  provider: ^6.1.2
  beamer: ^1.6.1
  flutter_svg: ^2.0.10+1
  minio_flutter: ^0.0.1
  universal_html: ^2.2.4
  uuid: ^4.4.0
  image_picker_for_web: ^3.0.4
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  mime: ^1.0.5
  image_cropper: ^6.0.0
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - graphics/heart.svg
  fonts:
    - family: Roobert
      fonts:
        - asset: fonts/Roobert-Regular.ttf